# -*- coding: utf-8 -*-
"""表 → 列映射（由 tools/extract_schema.py 从主程序 Models/*.cs 生成，请勿手改）。

重新生成：``python tools/extract_schema.py``
"""

TABLES = {
    "code_mappings": (
        ("Id", "INTEGER", False),
        ("CodeType", "NVARCHAR(1)", False),
        ("Code", "NVARCHAR(8)", False),
        ("Name", "NVARCHAR(64)", False),
    ),
    "stages": (
        ("Id", "INTEGER", False),
        ("Name", "NVARCHAR(32)", False),
        ("Description", "NVARCHAR(256)", True),
    ),
    "test_categories": (
        ("Id", "INTEGER", False),
        ("Name", "NVARCHAR(64)", False),
        ("Description", "NVARCHAR(256)", True),
    ),
    "products": (
        ("Id", "INTEGER", False),
        ("Name", "NVARCHAR(64)", False),
        ("Code", "NVARCHAR(32)", True),
        ("Remark", "NVARCHAR(256)", True),
    ),
    "model_mappings": (
        ("Id", "INTEGER", False),
        ("ModelName", "NVARCHAR(128)", False),
        ("Product", "NVARCHAR(64)", True),
        ("Customer", "NVARCHAR(64)", True),
    ),
    "plan_change_logs": (
        ("Id", "INTEGER", False),
        ("Action", "NVARCHAR(16)", False),
        ("PlanId", "INTEGER", False),
        ("Summary", "NVARCHAR(256)", True),
        ("BeforeJson", "NVARCHAR(0)", True),
        ("AfterJson", "NVARCHAR(0)", True),
        ("Operator", "NVARCHAR(64)", False),
        ("CreatedAt", "DATETIME", False),
    ),
    "app_settings": (
        ("Id", "INTEGER", False),
        ("Key", "NVARCHAR(64)", False),
        ("Value", "NVARCHAR(512)", True),
    ),
    "report_links": (
        ("Id", "INTEGER", False),
        ("JobNo", "NVARCHAR(64)", False),
        ("ReportDir", "NVARCHAR(512)", True),
        ("OverviewFile", "NVARCHAR(512)", True),
        ("UpdatedAt", "DATETIME", True),
    ),
    "mail_logs": (
        ("Id", "INTEGER", False),
        ("Kind", "NVARCHAR(16)", False),
        ("RefType", "NVARCHAR(32)", True),
        ("RefKey", "NVARCHAR(128)", True),
        ("Recipients", "NVARCHAR(1024)", True),
        ("Subject", "NVARCHAR(512)", True),
        ("Success", "BOOLEAN", False),
        ("Error", "NVARCHAR(1024)", True),
        ("CreatedAt", "DATETIME", False),
    ),
    "plans": (
        ("Id", "INTEGER", False),
        ("ModelName", "NVARCHAR(128)", True),
        ("TestItem", "NVARCHAR(128)", True),
        ("Remark", "NVARCHAR(512)", True),
        ("JobNo", "NVARCHAR(64)", True),
        ("Product", "NVARCHAR(64)", True),
        ("Customer", "NVARCHAR(64)", True),
        ("Stage", "NVARCHAR(32)", True),
        ("SampleSize", "NVARCHAR(32)", True),
        ("TestPeriod", "NVARCHAR(32)", True),
        ("Owner", "NVARCHAR(64)", True),
        ("StartDate", "DATETIME", True),
        ("EndDate", "DATETIME", True),
        ("Status", "NVARCHAR(32)", True),
        ("ReportStatus", "NVARCHAR(16)", True),
        ("UploadELab", "NVARCHAR(32)", True),
        ("UnitReturnDate", "DATETIME", True),
        ("CreatedBy", "NVARCHAR(64)", True),
        ("CreatedAt", "DATETIME", True),
        ("UpdatedBy", "NVARCHAR(64)", True),
        ("UpdatedAt", "DATETIME", True),
    ),
    "requisitions": (
        ("Id", "INTEGER", False),
        ("RequisitionDate", "DATETIME", True),
        ("RequisitionNo", "NVARCHAR(64)", True),
        ("ModelName", "NVARCHAR(128)", True),
        ("OutQty", "NVARCHAR(32)", True),
        ("Disposition", "NVARCHAR(16)", True),
        ("SN", "NVARCHAR(2048)", True),
        ("SnFilePath", "NVARCHAR(512)", True),
        ("Rev", "NVARCHAR(32)", True),
        ("WorkOrder", "NVARCHAR(64)", True),
        ("DC", "NVARCHAR(32)", True),
        ("LineNo", "NVARCHAR(32)", True),
        ("ReturnRtOrder", "NVARCHAR(64)", True),
        ("ReturnQty", "NVARCHAR(32)", True),
        ("ReturnDate", "DATETIME", True),
        ("StockInNo", "NVARCHAR(64)", True),
        ("StockInQty", "NVARCHAR(32)", True),
        ("StockInDate", "DATETIME", True),
        ("ScrapNo", "NVARCHAR(64)", True),
        ("ScrapQty", "NVARCHAR(32)", True),
        ("ScrapDate", "DATETIME", True),
        ("ScrapSnText", "NVARCHAR(0)", True),
        ("ScrapSnFilePath", "NVARCHAR(512)", True),
        ("Remark", "NVARCHAR(512)", True),
        ("CreatedBy", "NVARCHAR(64)", True),
        ("CreatedAt", "DATETIME", True),
        ("UpdatedBy", "NVARCHAR(64)", True),
        ("UpdatedAt", "DATETIME", True),
    ),
    "review_requests": (
        ("Id", "INTEGER", False),
        ("Type", "NVARCHAR(32)", False),
        ("Action", "NVARCHAR(16)", False),
        ("TargetId", "INTEGER", True),
        ("Summary", "NVARCHAR(256)", True),
        ("PayloadJson", "NVARCHAR(0)", True),
        ("RequesterName", "NVARCHAR(64)", False),
        ("AssigneeName", "NVARCHAR(64)", True),
        ("Status", "NVARCHAR(16)", False),
        ("ReviewerName", "NVARCHAR(64)", True),
        ("ReviewComment", "NVARCHAR(512)", True),
        ("CreatedAt", "DATETIME", False),
        ("ReviewedAt", "DATETIME", True),
    ),
    "customers": (
        ("Id", "INTEGER", False),
        ("Name", "NVARCHAR(64)", False),
        ("Code", "NVARCHAR(32)", True),
        ("Remark", "NVARCHAR(256)", True),
    ),
    "test_items_catalog": (
        ("Id", "INTEGER", False),
        ("Name", "NVARCHAR(128)", False),
        ("Period", "NVARCHAR(32)", True),
        ("Category", "NVARCHAR(64)", True),
        ("Owner", "NVARCHAR(64)", True),
        ("OwnerIds", "NVARCHAR(256)", True),
        ("Remark", "NVARCHAR(256)", True),
    ),
    "plan_item_templates": (
        ("Id", "INTEGER", False),
        ("TestItemName", "NVARCHAR(128)", False),
        ("Category", "NVARCHAR(128)", True),
        ("SamplingPlan", "NVARCHAR(0)", True),
        ("TestCondition", "NVARCHAR(0)", True),
        ("PassCriterion", "NVARCHAR(0)", True),
        ("Remark", "NVARCHAR(0)", True),
        ("Period", "NVARCHAR(64)", True),
        ("UsageCount", "INTEGER", False),
        ("IsManual", "BOOLEAN", False),
        ("CreatedBy", "NVARCHAR(64)", True),
        ("CreatedAt", "DATETIME", True),
        ("UpdatedBy", "NVARCHAR(64)", True),
        ("UpdatedAt", "DATETIME", True),
    ),
    "test_plans": (
        ("Id", "INTEGER", False),
        ("ModelName", "NVARCHAR(128)", False),
        ("Stage", "NVARCHAR(16)", False),
        ("Remark", "NVARCHAR(0)", True),
        ("Source", "NVARCHAR(16)", True),
        ("CreatedBy", "NVARCHAR(64)", True),
        ("CreatedAt", "DATETIME", True),
        ("UpdatedBy", "NVARCHAR(64)", True),
        ("UpdatedAt", "DATETIME", True),
    ),
    "test_plan_items": (
        ("Id", "INTEGER", False),
        ("PlanId", "INTEGER", False),
        ("OrderNo", "INTEGER", False),
        ("Category", "NVARCHAR(128)", True),
        ("TestItemName", "NVARCHAR(128)", False),
        ("TemplateId", "INTEGER", True),
        ("SamplingPlan", "NVARCHAR(0)", True),
        ("TestCondition", "NVARCHAR(0)", True),
        ("PassCriterion", "NVARCHAR(0)", True),
        ("Remark", "NVARCHAR(0)", True),
        ("Period", "NVARCHAR(64)", True),
        ("OverriddenFields", "NVARCHAR(256)", True),
        ("Confirmed", "BOOLEAN", False),
        ("SourceVariants", "NVARCHAR(0)", True),
        ("FromIndex", "BOOLEAN", False),
        ("UpdatedBy", "NVARCHAR(64)", True),
        ("UpdatedAt", "DATETIME", True),
    ),
    "plan_index_jobs": (
        ("Id", "INTEGER", False),
        ("Status", "NVARCHAR(16)", False),
        ("RootPath", "NVARCHAR(512)", True),
        ("Total", "INTEGER", False),
        ("Processed", "INTEGER", False),
        ("Failed", "INTEGER", False),
        ("Message", "NVARCHAR(512)", True),
        ("StartedBy", "NVARCHAR(64)", True),
        ("ClaimedBy", "NVARCHAR(128)", True),
        ("ClaimedAt", "DATETIME", True),
        ("StartedAt", "DATETIME", True),
        ("FinishedAt", "DATETIME", True),
        ("UpdatedAt", "DATETIME", True),
    ),
    "plan_index_entries": (
        ("Id", "INTEGER", False),
        ("JobId", "INTEGER", False),
        ("FolderName", "NVARCHAR(256)", True),
        ("ModelName", "NVARCHAR(128)", True),
        ("Stage", "NVARCHAR(16)", True),
        ("OverviewFile", "NVARCHAR(512)", True),
        ("Status", "NVARCHAR(16)", False),
        ("ItemCount", "INTEGER", False),
        ("Note", "NVARCHAR(1024)", True),
        ("Error", "NVARCHAR(512)", True),
        ("ClaimedBy", "NVARCHAR(128)", True),
        ("ClaimedAt", "DATETIME", True),
        ("UpdatedAt", "DATETIME", True),
    ),
    "plan_index_raw_items": (
        ("Id", "INTEGER", False),
        ("JobId", "INTEGER", False),
        ("EntryId", "INTEGER", False),
        ("ModelName", "NVARCHAR(128)", True),
        ("Stage", "NVARCHAR(16)", True),
        ("Category", "NVARCHAR(128)", True),
        ("TestItemName", "NVARCHAR(128)", True),
        ("OrderNo", "INTEGER", False),
        ("SamplingPlan", "NVARCHAR(0)", True),
        ("TestCondition", "NVARCHAR(0)", True),
        ("PassCriterion", "NVARCHAR(0)", True),
        ("Remark", "NVARCHAR(0)", True),
    ),
    "plan_item_images": (
        ("Id", "INTEGER", False),
        ("NameKey", "NVARCHAR(128)", False),
        ("TestItemName", "NVARCHAR(128)", True),
        ("ModelName", "NVARCHAR(128)", True),
        ("SourceFile", "NVARCHAR(512)", True),
        ("FileName", "NVARCHAR(256)", True),
        ("WidthPx", "INTEGER", False),
        ("HeightPx", "INTEGER", False),
        ("AnchorColumn", "INTEGER", False),
        ("AnchorColumn2", "INTEGER", False),
        ("OrderNo", "INTEGER", False),
        ("UpdatedAt", "DATETIME", True),
    ),
    "users": (
        ("Id", "INTEGER", False),
        ("Username", "NVARCHAR(64)", False),
        ("DisplayName", "NVARCHAR(64)", True),
        ("Email", "NVARCHAR(128)", True),
        ("PasswordHash", "NVARCHAR(128)", False),
        ("Salt", "NVARCHAR(64)", False),
        ("IsActive", "BOOLEAN", False),
        ("CreatedAt", "DATETIME", False),
    ),
    "user_roles": (
        ("Id", "INTEGER", False),
        ("UserId", "INTEGER", False),
        ("Role", "NVARCHAR(32)", False),
    ),
}

TABLE_NAMES = tuple(sorted(TABLES))


def columns_of(table):
    """返回列名元组；表不存在时返回空元组。"""
    return tuple(item[0] for item in TABLES.get(table, ()))


def sql_type_of(table, column):
    for name, sql_type, _nullable in TABLES.get(table, ()):
        if name == column:
            return sql_type
    return None
